### ISSUE TITLE
need some color changes for accessibility

### ISSUE THREAD

**Issue by mbeckett58** [canucklegame/canuckle#15]
i am partially red/green color blind and i can't see the difference between the red letters and the green letters. if you can change the colors to something with better contrast so color challenged individuals like myself can actually play, it would be much appreciated. thanks!

btw... i can see the difference in the original NYT game, although that one could do with better contrast as well.

**Comment by canucklegame** [comment]
Hi @mbeckett58 - Canuckle has a **High Contrast Mode** option in the **Settings** for improved colour vision. Have you tried that out? Wordle has the same option.

Canuckle doesn't have any green letters. Just red for correct letters, yellow/gold for right letter in the wrong spot, and grey for incorrect letters. In High Contrast Mode, correct letters are orange, and right letters in the wrong spot are light blue.

 Let us know which colours could use better contrast. Thanks for reaching out!

**Comment by canucklegame** [comment]
High Contrast Mode should address any colour contrast issues.
